### ISSUE TITLE
swUserPreferenceIntegerValue_e.swExportSTLQuality needed

### ISSUE THREAD

**Issue by thopiekar** [tdsmith/swharness#1]
Hey @tdsmith 

where did you get all the enums from?
I currently miss in your great list of enums swUserPreferenceIntegerValue_e.swExportSTLQuality 😕 Can you help?

Thanks!

**Comment by tdsmith** [comment]
I used makepy, installed by https://pypi.python.org/pypi/pypiwin32; see http://timgolden.me.uk/pywin32-docs/html/com/win32com/HTML/QuickStartClientCom.html.
